# Makefile for installing the x86 toolchain script in Linux

# Created by Amos Leung
# ISS Program, SADT, SAIT
# October 2023


install:
# Copy "x86_toolchain.sh" to "/usr/local/bin" directory and make it executable
	cp x86_toolchain.sh /usr/local/bin
	chmod +x /usr/local/bin/x86_toolchain.sh

uninstall:
# Remove "x86_toolchain.sh" from "/usr/local/bin" directory
    rm /usr/local/bin/x86_toolchain.sh
